services:
  web:
    image: ${DOCKER_USERNAME}/forege_dialog
    build:
      context: .
      dockerfile: ForegeDialog/Web/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: always
    volumes:
      - ./uploads:/app/wwwroot/uploads
